version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * 0"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * 0"
